core/urls.py
from django.urls import path
from . import  views
from .views import DetalharPetView

app_name = 'core'
urlpatterns=[
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', DetalharPetView.as_view(), name='detalhar_pet'),
]

trabalhofinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from stdimage.models import StdImageField


class Base(models.Model):
    criado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)
    ativo = models.BooleanField(default=True)

    class Meta:
        abstract = True


class Cargo(models.Model):
    cargo = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Cargo'
        verbose_name_plural = 'Cargos'

    def __str__(self):
        return self.cargo


class Funcionario(Base):
    nome = models.CharField('Nome', max_length = 100)
    descricao = models.TextField('Descrição', max_length =100)
    cargo = models.ForeignKey('core.Cargo', on_delete = models.SET_NULL, null = True)
    foto = StdImageField('Foto', upload_to='equipe', variations={'thumb':{'width': 410, 'height': 410, 'crop': True}})
    instagram = models.CharField('Instagram', max_length=100)

    class Meta:
        verbose_name = 'Funcionário'
        verbose_name_plural = 'Funcionários'

    def __str__(self):
        return self.nome


class Animal(models.Model):
    animal = models.CharField(max_length = 50)

    class Meta:
        verbose_name = 'Animal'
        verbose_name_plural = 'Animais'

    def __str__(self):
        return self.animal


class Pet (Base):
    nome = models.CharField('Nome', max_length = 100)
    descricao = models.TextField('Descrição', max_length = 1000)
    animal = models.ForeignKey('core.Animal', on_delete = models.SET_NULL, null = True)
    foto = StdImageField('Foto', upload_to='Pets', variations={'thumb': {'width': 410, 'height': 275, 'crop': True}})

    class Meta:
        verbose_name = 'Pet'
        verbose_name_plural = 'Pets'

    def __str__(self):
        return self.nome


class Social(Base):
    twitter = models.CharField('Twitter', max_length=100)
    facebook = models.CharField('Facebook', max_length=100)
    youtube = models.CharField('Youtube', max_length=100)
    instagram = models.CharField('Instagram', max_length=100)

    class Meta:
        verbose_name = 'Social'
        verbose_name_plural = 'Sociais'





# Create your models here.

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView

from core.models import Pet, Funcionario, Social


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['pets'] = Pet.objects.all()
        context['funcionarios'] = Funcionario.objects.all()
        context['sociais'] = Social.objects.all()
        return context

class DetalharPetView(DetailView):
    template_name = 'detalhar_pet.html'
    model = Pet


# Create your views here.

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v5.6.8, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v5.6.8, mobirise.com">
  <meta name="twitter:card" content="summary_large_image"/>
  <meta name="twitter:image:src" content="">
  <meta property="og:image" content="">
  <meta name="twitter:title" content="Home">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/x-icon">
  <meta name="description" content="">


  <title>Home</title>
  <link rel="stylesheet" href="{% static 'web/assets/mobirise-icons2/mobirise2.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'socicon/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'theme/css/style.css' %}">
  <link rel="preload" href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"></noscript>
  <link rel="preload" as="style" href="{% static 'mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'mobirise/css/mbr-additional.css' %}" type="text/css">




</head>
<body>

  <section data-bs-version="5.1" class="menu menu1 cid-t9qNhKP67x" once="menu" id="menu1-0">


    <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
        <div class="container-fluid">
            <div class="navbar-brand">

                <span class="navbar-caption-wrap"><a class="navbar-caption text-black display-7" href="{% url 'core:index' %}">AdoteC&amp;G</a></span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true"><li class="nav-item"><a class="nav-link link text-black text-primary display-4" href="{% url 'core:index' %}#top">Topo</a></li>
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4" href="{% url 'core:index' %}#features12-5">Sobre</a></li>
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4" href="{% url 'core:index' %}#features3-6">Pets</a>
                    </li><li class="nav-item"><a class="nav-link link text-black text-primary display-4" href="{% url 'core:index' %}#gallery4-7">Galeria</a></li><li class="nav-item"><a class="nav-link link text-black text-primary display-4" href="{% url 'core:index' %}#team1-8">Nossa Equipe</a></li><li class="nav-item"><a class="nav-link link text-black text-primary display-4" href="{% url 'core:index' %}#form5-9">Entre em Contato</a></li><li class="nav-item"><a class="nav-link link text-black text-primary display-4" href="{% url 'core:index' %}#contacts4-a">Nossas Mídias</a></li></ul>


            </div>
        </div>
    </nav>
</section>


{% block conteudo %}{% endblock %}

<section data-bs-version="5.1" class="footer7 cid-t9qOVoNMep" once="footers" id="footer7-b">





    <div class="container">
        <div class="media-container-row align-center mbr-white">
            <div class="col-12">
                <p class="mbr-text mb-0 mbr-fonts-style display-7">
                    © Copyright 2025 Mobirise - All Rights Reserved
                </p>
            </div>
        </div>
    </div>
</section><section class="display-7" style="padding: 0;align-items: center;justify-content: center;flex-wrap: wrap;    align-content: center;display: flex;position: relative;height: 4rem;"><a href="https://mobiri.se/2800967" style="flex: 1 1;height: 4rem;position: absolute;width: 100%;z-index: 1;"><img alt="" style="height: 4rem;" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="></a><p style="margin: 0;text-align: center;" class="display-7">Built with Mobirise &#8204;</p><a style="z-index:1" href="https://mobirise.com/html-builder.html">Free HTML5 Site Generator</a></section><script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>  <script src="{% static 'smoothscroll/smooth-scroll.js' %}"></script>  <script src="{% static 'ytplayer/index.js' %}"></script>  <script src="{% static 'dropdown/js/navbar-dropdown.js' %}"></script>  <script src="{% static 'sociallikes/social-likes.js' %}"></script>  <script src="{% static 'theme/js/script.js' %}"></script>  <script src="{% static 'formoid/formoid.min.js' %}"></script>


</body>
</html>

core/templates/detalhar_pet.html
{% extends 'base.html'%}
{% load static %}

{% block conteudo %}
    <div class="container">
        <div class="item-img">
            <img src="{{ pet.foto.url }}" alt="Imagem do Pet">
        </div>
        <div class="container">
            <h1>
                {{ pet.nome }}
            </h1>
            <p>
                {{ pet.descricao }}
            </p>
        </div>
    </div>
{% endblock %}

core/templates/equipe.html
{% load static %}
<section data-bs-version="5.1" class="team1 cid-t9qOSA3hud" id="team1-8">



    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <h3 class="mbr-section-title mbr-fonts-style align-center mb-4 display-2">
                    <strong>Nosso Time</strong></h3>

            </div>
            {% for f in funcionarios %}
            <div class="col-sm-6 col-lg-4">
                <div class="card-wrap">
                    <div class="image-wrap">
                        <img src="{{ f.foto.thumb.url }}" alt="Mobirise Website Builder">
                    </div>
                    <div class="content-wrap">
                        <h5 class="mbr-section-title card-title mbr-fonts-style align-center m-0 display-5">
                            <strong>{{ f.nome }}</strong>
                        </h5>
                        <h6 class="mbr-role mbr-fonts-style align-center mb-3 display-4">
                            <strong>{{ f.cargo }}</strong></h6>
                        <p class="card-text mbr-fonts-style align-center display-7">
                        {{ f.descricao }}
                        </p>

                        <div class="mbr-section-btn card-btn align-center"><a class="btn btn-primary display-4" href="{{ f.instagram }}"><span class="socicon socicon-instagram mbr-iconfont mbr-iconfont-btn"></span>Veja o Perfil</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>

core/templates/galeria.html
{% load static %}
<section data-bs-version="5.1" class="gallery4 mbr-gallery cid-t9qOO9Dwb0" id="gallery4-7">




    <div class="container-fluid">
        <div class="mbr-section-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center m-0 display-2"><strong>Pets já adotados!</strong></h3>
            <h4 class="mbr-section-subtitle mbr-fonts-style align-center mb-0 mt-2 display-5"></h4>
        </div>
        <div class="row mbr-gallery mt-4">
            <div class="col-12 col-md-6 col-lg-4 item gallery-image">
                <div class="item-wrapper" data-toggle="modal" data-bs-toggle="modal" data-target="#t9sdlqniwK-modal" data-bs-target="#t9sdlqniwK-modal">
                    <img class="w-100" src="{% static 'images/mbr-1181x664.jpg' %}" alt="Mobirise Website Builder" data-slide-to="0" data-bs-slide-to="0" data-target="#lb-t9sdlqniwK" data-bs-target="#lb-t9sdlqniwK">
                    <div class="icon-wrapper">
                        <span class="mobi-mbri mobi-mbri-search mbr-iconfont mbr-iconfont-btn"></span>
                    </div>
                </div>

            </div>
            <div class="col-12 col-md-6 col-lg-4 item gallery-image">
                <div class="item-wrapper" data-toggle="modal" data-bs-toggle="modal" data-target="#t9sdlqniwK-modal" data-bs-target="#t9sdlqniwK-modal">
                    <img class="w-100" src="{% static 'images/mbr-1181x787.jpg' %}" alt="Mobirise Website Builder" data-slide-to="1" data-bs-slide-to="1" data-target="#lb-t9sdlqniwK" data-bs-target="#lb-t9sdlqniwK">
                    <div class="icon-wrapper">
                        <span class="mobi-mbri mobi-mbri-search mbr-iconfont mbr-iconfont-btn"></span>
                    </div>
                </div>

            </div>
            <div class="col-12 col-md-6 col-lg-4 item gallery-image">
                <div class="item-wrapper" data-toggle="modal" data-bs-toggle="modal" data-target="#t9sdlqniwK-modal" data-bs-target="#t9sdlqniwK-modal">
                    <img class="w-100" src="{% static 'images/mbr-1181x1772.jpg' %}" alt="Mobirise Website Builder" data-slide-to="2" data-bs-slide-to="2" data-target="#lb-t9sdlqniwK" data-bs-target="#lb-t9sdlqniwK">
                    <div class="icon-wrapper">
                        <span class="mobi-mbri mobi-mbri-search mbr-iconfont mbr-iconfont-btn"></span>
                    </div>
                </div>

            </div>
            <div class="col-12 col-md-6 col-lg-4 item gallery-image">
                <div class="item-wrapper" data-toggle="modal" data-bs-toggle="modal" data-target="#t9sdlqniwK-modal" data-bs-target="#t9sdlqniwK-modal">
                    <img class="w-100" src="{% static 'images/mbr-1181x741.jpg' %}" alt="Mobirise Website Builder" data-slide-to="3" data-bs-slide-to="3" data-target="#lb-t9sdlqniwK" data-bs-target="#lb-t9sdlqniwK">
                    <div class="icon-wrapper">
                        <span class="mobi-mbri mobi-mbri-search mbr-iconfont mbr-iconfont-btn"></span>
                    </div>
                </div>

            </div><div class="col-12 col-md-6 col-lg-4 item gallery-image">
                <div class="item-wrapper" data-toggle="modal" data-bs-toggle="modal" data-target="#t9sdlqniwK-modal" data-bs-target="#t9sdlqniwK-modal">
                    <img class="w-100" src="{% static 'images/mbr-1181x738.jpg' %}" alt="Mobirise Website Builder" data-slide-to="4" data-bs-slide-to="4" data-target="#lb-t9sdlqniwK" data-bs-target="#lb-t9sdlqniwK">
                    <div class="icon-wrapper">
                        <span class="mobi-mbri mobi-mbri-search mbr-iconfont mbr-iconfont-btn"></span>
                    </div>
                </div>

            </div><div class="col-12 col-md-6 col-lg-4 item gallery-image">
                <div class="item-wrapper" data-toggle="modal" data-bs-toggle="modal" data-target="#t9sdlqniwK-modal" data-bs-target="#t9sdlqniwK-modal">
                    <img class="w-100" src="{% static 'images/mbr-1181x1234.jpg' %}" alt="Mobirise Website Builder" data-slide-to="5" data-bs-slide-to="5" data-target="#lb-t9sdlqniwK" data-bs-target="#lb-t9sdlqniwK">
                    <div class="icon-wrapper">
                        <span class="mobi-mbri mobi-mbri-search mbr-iconfont mbr-iconfont-btn"></span>
                    </div>
                </div>

            </div>
        </div>

        <div class="modal mbr-slider" tabindex="-1" role="dialog" aria-hidden="true" id="t9sdlqniwK-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="carousel slide" id="lb-t9sdlqniwK" data-interval="5000" data-bs-interval="5000">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <img class="d-block w-100" src="{% static 'images/mbr-1181x664.jpg' %}" alt="Mobirise Website Builder">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static 'images/mbr-1181x787.jpg' %}" alt="Mobirise Website Builder">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static 'images/mbr-1181x1772.jpg' %}" alt="Mobirise Website Builder">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static 'images/mbr-1181x741.jpg' %}" alt="Mobirise Website Builder">
                                </div><div class="carousel-item">
                                    <img class="d-block w-100" src="{% static 'images/mbr-1181x738.jpg' %}" alt="Mobirise Website Builder">
                                </div><div class="carousel-item">
                                    <img class="d-block w-100" src="{% static 'images/mbr-1181x1234.jpg' %}" alt="Mobirise Website Builder">
                                </div>
                            </div>
                            <ol class="carousel-indicators">
                                <li data-slide-to="0" data-bs-slide-to="0" class="active" data-target="#lb-t9sdlqniwK" data-bs-target="#lb-t9sdlqniwK"></li>
                                <li data-slide-to="1" data-bs-slide-to="1" data-target="#lb-t9sdlqniwK" data-bs-target="#lb-t9sdlqniwK"></li>
                                <li data-slide-to="2" data-bs-slide-to="2" data-target="#lb-t9sdlqniwK" data-bs-target="#lb-t9sdlqniwK"></li>
                                <li data-slide-to="3" data-bs-slide-to="3" data-target="#lb-t9sdlqniwK" data-bs-target="#lb-t9sdlqniwK"></li><li data-slide-to="4" data-bs-slide-to="4" data-target="#lb-t9sdlqniwK" data-bs-target="#lb-t9sdlqniwK"></li><li data-slide-to="5" data-bs-slide-to="5" data-target="#lb-t9sdlqniwK" data-bs-target="#lb-t9sdlqniwK"></li>
                            </ol>
                            <a role="button" href="" class="close" data-dismiss="modal" data-bs-dismiss="modal" aria-label="Close">
                            </a>
                            <a class="carousel-control-prev carousel-control" role="button" data-slide="prev" data-bs-slide="prev" href="#lb-t9sdlqniwK">
                                <span class="mobi-mbri mobi-mbri-arrow-prev" aria-hidden="true"></span>
                                <span class="sr-only visually-hidden">Previous</span>
                            </a>
                            <a class="carousel-control-next carousel-control" role="button" data-slide="next" data-bs-slide="next" href="#lb-t9sdlqniwK">
                                <span class="mobi-mbri mobi-mbri-arrow-next" aria-hidden="true"></span>
                                <span class="sr-only visually-hidden">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

core/templates/header.html
<section data-bs-version="5.1" class="header7 cid-t9sbNejR1H mbr-fullscreen" id="header7-d">

    <div class="text-right container">
        <div class="row justify-content-end">
            <div class="col-12 col-lg-5">
                <h1 class="mbr-section-title mbr-fonts-style mb-3 display-1"><strong>Adote Cães e Gatos</strong></h1>

                <p class="mbr-text mbr-fonts-style display-5">
                    Mobirise Free Website Maker is perfect for non-techies and great for pro-coders for fast prototyping and small customers' projects.</p>
            </div>
        </div>
    </div>
</section>

core/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block conteudo %}
    {% include 'header.html' %}
    {% include 'sobre.html' %}
    {% include 'pets.html' %}
    {% include 'galeria.html' %}
    {% include 'equipe.html' %}
    {% include 'sociais.html' %}

{% endblock %}

core/templates/pets.html
{% load static %}
<section data-bs-version="5.1" class="features3 cid-t9qONPUPzj" id="features3-6">


    <div class="container">
        <div class="mbr-section-head">
            <h4 class="mbr-section-title mbr-fonts-style align-center mb-5 display-2"><strong>Alguns Pets para Adoção</strong></h4>

        </div>
        <div class="row mt-4">
            {% for p in pets %}
            <div class="item features-image сol-12 col-md-6 col-lg-4">
                <div class="item-wrapper">
                    <div class="item-img">
                        <img src="{{ p.foto.thumb.url }}" alt="Mobirise Website Builder">
                    </div>
                    <div class="item-content">
                        <h5 class="item-title mbr-fonts-style display-5"><strong>{{ p.nome }}</strong></h5>

                        <p class="mbr-text mbr-fonts-style mt-3 display-7">{{p.descricao|truncatewords:20}}</p>
                    </div>
                    <div class="mbr-section-btn item-footer mt-2"><a href="{% url 'core:detalhar_pet' p.id %}" class="btn item-btn btn-secondary display-7" target="_blank">Leia Mais&nbsp;&gt;</a></div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

core/templates/sobre.html
{% load static %}
<section data-bs-version="5.1" class="features11 cid-t9qOMHoZnL" id="features12-5">



    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-lg">
                <div class="card-wrapper">
                    <div class="card-box">
                        <h4 class="card-title mbr-fonts-style mb-4 display-2">
                            <strong>Sobre o AdoteC&amp;G</strong></h4>
                        <p class="mbr-text mbr-fonts-style mb-4 display-7">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et lobortis lacus. Proin lorem sapien, fermentum id finibus at, molestie ultrices mi. Nulla ante elit, facilisis ac vehicula et, egestas id mauris. Aenean interdum elit in felis scelerisque, in interdum ante pulvinar.<br></p>
                        <div class="mbr-text mbr-fonts-style counter-container display-7">
                            <ul>
                                <li>Aenean Interdum</li><li>Felis scelerisque</li><li>Lorem Ipsum Dolor</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-6 md-pb">
                <div class="image-wrapper">
                    <img src="{% static 'images/mbr-2-1256x837.jpg' %}" alt="Mobirise Website Builder">
                </div>
            </div>
        </div>
    </div>
</section>

core/templates/sociais.html
{% load static %}
<section data-bs-version="5.1" class="contacts4 cid-t9qOV5o0Ro" id="contacts4-a">





    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="text-content col-12 col-md-6">
                <h2 class="mbr-section-title mbr-fonts-style display-2">
                    <strong>Siga nossas redes sociais!</strong></h2>
                <p class="mbr-text mbr-fonts-style display-7">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et lobortis lacus. Proin lorem sapien, fermentum id finibus at, molestie ultrices mi. Nulla ante elit, facilisis ac vehicula et, egestas id mauris. Aenean interdum elit in felis scelerisque, in interdum ante pulvinar.</p>
            </div>
            {% for s in sociais %}
            <div class="icons d-flex align-items-center col-12 col-md-6 justify-content-end mt-md-0 mt-2 flex-wrap">
                <a href="{{ s.twitter }}" target="_blank">
                    <span class="socicon-twitter socicon mbr-iconfont mbr-iconfont-social"></span>
                </a>
                <a href="{{ s.facebook }}" target="_blank">
                    <span class="socicon-facebook socicon mbr-iconfont mbr-iconfont-social"></span>
                </a>
                <a href="{{ s.youtube }}" target="_blank">
                    <span class="socicon-youtube socicon mbr-iconfont mbr-iconfont-social"></span>
                </a>
                <a href="{{ s.instagram }}" target="_blank">
                    <span class="socicon-instagram socicon mbr-iconfont mbr-iconfont-social"></span>
                </a>


            </div>
            {% endfor %}
        </div>
    </div>

</section>